import os
import tempfile
from time import sleep

# fmt: off
JOBS = [
    # ('r01_all', 'mignot,owners,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 01 -f all -k 5 -n 3 -c rbf'),
    # ('r03_all', 'mignot,owners,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 03 -f all -k 5 -n 3 -c rbf'),
    # ('r05_all', 'mignot,owners,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 05 -f all -k 5 -n 3 -c rbf'),
    # ('r10_all', 'mignot,owners,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 10 -f all -k 5 -n 3 -c rbf'),
    # ('r15_all', 'mignot,owners,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 15 -f all -k 5 -n 3 -c rbf'),
    # ('r30_all', 'mignot,owners,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 30 -f all -k 5 -n 3 -c rbf'),
    # ('r01_all', 'mignot,owners,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 01 -f preselected -k 5 -n 3 -c rbf'),
    # ('r03_all', 'mignot,owners,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 03 -f preselected -k 5 -n 3 -c rbf'),
    # ('r05_all', 'mignot,owners,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 05 -f preselected -k 5 -n 3 -c rbf'),
    # ('r10_all', 'mignot,owners,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 10 -f preselected -k 5 -n 3 -c rbf'),
    # ('r15_all', 'mignot,owners,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 15 -f preselected -k 5 -n 3 -c rbf'),
    # ('r30_all', 'mignot,owners,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 30 -f preselected -k 5 -n 3 -c rbf'),
    # ('r01_all', 'mignot,owners,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 01 -f all -k 5 -n 3 -c rq'),
    # ('r03_rq_all', 'mignot,owners,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 03 -f all -k 5 -n 3 -c rq'),
    # ('r05_rq_all', 'mignot,owners,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 05 -f all -k 5 -n 3 -c rq'),
    # ('r10_rq_all', 'mignot,owners,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 10 -f all -k 5 -n 3 -c rq'),
    # ('r15_rq_all', 'mignot,owners,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 15 -f all -k 5 -n 3 -c rq'),
    # ('r30_rq_all', 'mignot,owners,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 30 -f all -k 5 -n 3 -c rq'),
    # ('r01_all', 'mignot,owners,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 01 -f preselected -k 5 -n 3 -c rq'),
    # ('r03_all', 'mignot,owners,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 03 -f preselected -k 5 -n 3 -c rq'),
    # ('r05_all', 'mignot,owners,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 05 -f preselected -k 5 -n 3 -c rq'),
    # ('r10_all', 'mignot,owners,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 10 -f preselected -k 5 -n 3 -c rq'),
    # ('r15_all', 'mignot,owners,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 15 -f preselected -k 5 -n 3 -c rq'),
    # ('r30_all', 'mignot,owners,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 30 -f preselected -k 5 -n 3 -c rq'),
    # ('r01_rbf_all_kmeans', 'mignot,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 01 -f all -k 5 -n 3 -c rbf --inducing kmeans'),
    # ('r03_rbf_all_kmeans', 'mignot,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 03 -f all -k 5 -n 3 -c rbf --inducing kmeans'),
    # ('r05_rbf_all_kmeans', 'mignot,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 05 -f all -k 5 -n 3 -c rbf --inducing kmeans'),
    # ('r10_rbf_all_kmeans', 'mignot,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 10 -f all -k 5 -n 3 -c rbf --inducing kmeans'),
    # ('r15_rbf_all_kmeans', 'mignot,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 15 -f all -k 5 -n 3 -c rbf --inducing kmeans'),
    # ('r30_rbf_all_kmeans', 'mignot,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 30 -f all -k 5 -n 3 -c rbf --inducing kmeans'),
    # ('r01_rbf_preselected_kmeans', 'mignot,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 01 -f preselected -k 5 -n 3 -c rbf --inducing kmeans'),
    # ('r03_rbf_preselected_kmeans', 'mignot,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 03 -f preselected -k 5 -n 3 -c rbf --inducing kmeans'),
    # ('r05_rbf_preselected_kmeans', 'mignot,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 05 -f preselected -k 5 -n 3 -c rbf --inducing kmeans'),
    # ('r10_rbf_preselected_kmeans', 'mignot,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 10 -f preselected -k 5 -n 3 -c rbf --inducing kmeans'),
    # ('r15_rbf_preselected_kmeans', 'mignot,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 15 -f preselected -k 5 -n 3 -c rbf --inducing kmeans'),
    # ('r30_rbf_preselected_kmeans', 'mignot,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 30 -f preselected -k 5 -n 3 -c rbf --inducing kmeans'),
    # ('r01_rq_all_kmeans', 'mignot,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 01 -f all -k 5 -n 3 -c rq --inducing kmeans'),
    # ('r03_rq_all_kmeans', 'mignot,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 03 -f all -k 5 -n 3 -c rq --inducing kmeans'),
    # ('r05_rq_all_kmeans', 'mignot,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 05 -f all -k 5 -n 3 -c rq --inducing kmeans'),
    # ('r10_rq_all_kmeans', 'mignot,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 10 -f all -k 5 -n 3 -c rq --inducing kmeans'),
    # ('r15_rq_all_kmeans', 'mignot,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 15 -f all -k 5 -n 3 -c rq --inducing kmeans'),
    # ('r30_rq_all_kmeans', 'mignot,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 30 -f all -k 5 -n 3 -c rq --inducing kmeans'),
    # ('r01_rq_preselected_kmeans', 'mignot,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 01 -f preselected -k 5 -n 3 -c rq --inducing kmeans'),
    # ('r03_rq_preselected_kmeans', 'mignot,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 03 -f preselected -k 5 -n 3 -c rq --inducing kmeans'),
    # ('r05_rq_preselected_kmeans', 'mignot,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 05 -f preselected -k 5 -n 3 -c rq --inducing kmeans'),
    # ('r10_rq_preselected_kmeans', 'mignot,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 10 -f preselected -k 5 -n 3 -c rq --inducing kmeans'),
    # ('r15_rq_preselected_kmeans', 'mignot,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 15 -f preselected -k 5 -n 3 -c rq --inducing kmeans'),
    # ('r30_rq_preselected_kmeans', 'mignot,gpu', '24:00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 30 -f preselected -k 5 -n 3 -c rq --inducing kmeans'),
    # ('r03-rq-all-n16-k10-kmeans', 'mignot', '4-00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 03 -f all -k 10 -n 16 -c rq --inducing kmeans'),
    # ('r03-rq-all-n16-k10-kmeans', 'mignot', '4-00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 03 -f all -k 10 -n 16 -c rq --inducing kmeans'),
    # ('r01-rq-all-n16-k05-kmeans', 'mignot', '4-00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 01 -f all -k 05 -n 16 -c rq --inducing kmeans'),
    # ('r05-rq-all-n16-k05-kmeans', 'mignot', '4-00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 05 -f all -k 05 -n 16 -c rq --inducing kmeans'),
    # ('r10-rq-all-n16-k05-kmeans', 'mignot', '4-00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 10 -f all -k 05 -n 16 -c rq --inducing kmeans'),
    # ('r15-rq-all-n16-k05-kmeans', 'mignot', '4-00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 15 -f all -k 05 -n 16 -c rq --inducing kmeans'),
    # ('r30-rq-all-n16-k05-kmeans', 'mignot', '4-00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -r 30 -f all -k 05 -n 16 -c rq --inducing kmeans'),
    # ('filtered_10000', 'mignot,gpu', '2-00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -f filtered -k 05 -n 16 -c rq --inducing kmeans -l bernoulli -s experiments/filtered --n_iter 10000'),
    # ('filtered_15000', 'mignot,gpu', '2-00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -f filtered -k 05 -n 16 -c rq --inducing kmeans -l bernoulli -s experiments/filtered_n15000 --n_iter 15000'),
    # ('filtered_20000', 'mignot,gpu', '2-00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -f filtered -k 05 -n 16 -c rq --inducing kmeans -l bernoulli -s experiments/filtered_n20000 --n_iter 20000'),
    # ('filtered_long_n10000', 'mignot,gpu', '2-00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -f filtered_long -k 05 -n 16 -c rq --inducing kmeans -l bernoulli -s experiments/filtered_long_n10000 --n_iter 10000'),
    # ('filtered_long_n15000', 'mignot,gpu', '2-00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -f filtered_long -k 05 -n 16 -c rq --inducing kmeans -l bernoulli -s experiments/filtered_long_n15000 --n_iter 15000'),
    # ('filtered_long_n20000', 'mignot,gpu', '2-00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -f filtered_long -k 05 -n 16 -c rq --inducing kmeans -l bernoulli -s experiments/filtered_long_n20000 --n_iter 20000'),
    # ('final_r01', 'mignot,gpu', '2-00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -f all -r 01 -k 05 -n 5 -c rq --inducing kmeans -l bernoulli -s experiments/final_r01 --n_iter 50000'),
    # ('final_r03', 'mignot,gpu', '2-00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -f all -r 03 -k 05 -n 5 -c rq --inducing kmeans -l bernoulli -s experiments/final_r03 --n_iter 50000'),
    # ('final_r05', 'mignot,gpu', '2-00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -f all -r 05 -k 05 -n 5 -c rq --inducing kmeans -l bernoulli -s experiments/final_r05 --n_iter 50000'),
    # ('final_r10', 'mignot,gpu', '2-00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -f all -r 10 -k 05 -n 5 -c rq --inducing kmeans -l bernoulli -s experiments/final_r10 --n_iter 50000'),
    # ('final_r15', 'mignot,gpu', '2-00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -f all -r 15 -k 05 -n 5 -c rq --inducing kmeans -l bernoulli -s experiments/final_r15 --n_iter 50000'),
    # ('final_r30', 'mignot,gpu', '2-00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -f all -r 30 -k 05 -n 5 -c rq --inducing kmeans -l bernoulli -s experiments/final_r30 --n_iter 50000'),
    # ('final_filtered', 'mignot,gpu', '2-00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -f filtered -k 05 -n 5 -c rq --inducing kmeans -l bernoulli -s experiments/final_filtered --n_iter 50000'),
    # ('final_filtered_long', 'mignot,gpu', '2-00:00', '5', '1', 'python train_gp_model.py -m avg_kw21 -f filtered_long -k 05 -n 5 -c rq --inducing kmeans -l bernoulli -s experiments/final_filtered_long --n_iter 50000'),
    # ('final_r03', 'mignot,gpu', '2-00:00', '5', '1', {'model': '-m avg_kw21', 'feature_set': '-f all', 'resolution': '-r 03', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'inducing': '--inducing kmeans', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/final_r03', 'niter': '--n_iter 50000'}),
    # ('final_r05', 'mignot,gpu', '2-00:00', '5', '1', {'model': '-m avg_kw21', 'feature_set': '-f all', 'resolution': '-r 05', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'inducing': '--inducing kmeans', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/final_r05', 'niter': '--n_iter 50000'}),
    # ('final_r10', 'mignot,gpu', '2-00:00', '5', '1', {'model': '-m avg_kw21', 'feature_set': '-f all', 'resolution': '-r 10', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'inducing': '--inducing kmeans', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/final_r10', 'niter': '--n_iter 50000'}),
    # ('final_r15', 'mignot,gpu', '2-00:00', '5', '1', {'model': '-m avg_kw21', 'feature_set': '-f all', 'resolution': '-r 15', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'inducing': '--inducing kmeans', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/final_r15', 'niter': '--n_iter 50000'}),
    # ('final_r30', 'mignot,gpu', '2-00:00', '5', '1', {'model': '-m avg_kw21', 'feature_set': '-f all', 'resolution': '-r 30', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'inducing': '--inducing kmeans', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/final_r30', 'niter': '--n_iter 50000'}),
    # ('final_r60', 'mignot,owners,gpu', '2-00:00', '5', '1', {'model': '-m avg_kw21', 'feature_set': '-f all', 'resolution': '-r 60', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'inducing': '--inducing kmeans', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/final_r60', 'niter': '--n_iter 50000'}),
    # ('final_r150', 'mignot,owners,gpu', '2-00:00', '5', '1', {'model': '-m avg_kw21', 'feature_set': '-f all', 'resolution': '-r 150', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'inducing': '--inducing kmeans', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/final_r150', 'niter': '--n_iter 50000'}),
    # ('final_r300', 'mignot,owners,gpu', '2-00:00', '5', '1', {'model': '-m avg_kw21', 'feature_set': '-f all', 'resolution': '-r 300', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'inducing': '--inducing kmeans', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/final_r300', 'niter': '--n_iter 50000'}),
    # ('final_r600', 'mignot,owners,gpu', '2-00:00', '5', '1', {'model': '-m avg_kw21', 'feature_set': '-f all', 'resolution': '-r 600', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'inducing': '--inducing kmeans', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/final_r600', 'niter': '--n_iter 50000'}),
    # ('final_r900', 'mignot,owners,gpu', '2-00:00', '5', '1', {'model': '-m avg_kw21', 'feature_set': '-f all', 'resolution': '-r 900', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'inducing': '--inducing kmeans', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/final_r900', 'niter': '--n_iter 50000'}),
    # ('final_r1800', 'mignot,owners,gpu', '2-00:00', '5', '1', {'model': '-m avg_kw21', 'feature_set': '-f all', 'resolution': '-r 1800', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'inducing': '--inducing kmeans', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/final_r1800', 'niter': '--n_iter 50000'}),
    # ('final_r2700', 'mignot,owners,gpu', '2-00:00', '5', '1', {'model': '-m avg_kw21', 'feature_set': '-f all', 'resolution': '-r 2700', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'inducing': '--inducing kmeans', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/final_r2700', 'niter': '--n_iter 50000'}),
    # ('final_r3600', 'mignot,owners,gpu', '2-00:00', '5', '1', {'model': '-m avg_kw21', 'feature_set': '-f all', 'resolution': '-r 3600', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'inducing': '--inducing kmeans', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/final_r3600', 'niter': '--n_iter 50000'}),
    # ('final_r5400', 'mignot,owners,gpu', '2-00:00', '5', '1', {'model': '-m avg_kw21', 'feature_set': '-f all', 'resolution': '-r 5400', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'inducing': '--inducing kmeans', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/final_r5400', 'niter': '--n_iter 50000'}),
    # ('final_r7200', 'mignot,owners,gpu', '2-00:00', '5', '1', {'model': '-m avg_kw21', 'feature_set': '-f all', 'resolution': '-r 7200', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'inducing': '--inducing kmeans', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/final_r7200', 'niter': '--n_iter 50000'}),
    # ('final_filtered', 'mignot,owners,gpu', '2-00:00', '5', '1', {'model': '-m avg_kw21', 'feature_set': '-f filtered', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'inducing': '--inducing kmeans', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/final_filtered', 'niter': '--n_iter 50000'}),
    # ('final_filtered_long', 'mignot,owners,gpu', '2-00:00', '5', '1', {'model': '-m avg_kw21', 'feature_set': '-f filtered_long', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'inducing': '--inducing kmeans', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/final_filtered_long', 'niter': '--n_iter 50000'}),
    # ('filtered_vgp', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'gp_model': '--gp_model vgp', 'feature_set': '-f filtered', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/filtered_vgp', 'niter': '--n_iter 50000'}),
    # ('filtered_vgp', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'gp_model': '--gp_model vgp', 'feature_set': '-f filtered_long', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/filtered_long_vgp', 'niter': '--n_iter 50000'}),
    # ('r01_vgp', 'mignot,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 01', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r01_vgp', 'niter': '--n_iter 50000'}),
    # ('r03_vgp', 'mignot,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 03', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r03_vgp', 'niter': '--n_iter 50000'}),
    # ('r05_vgp', 'mignot,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 05', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r05_vgp', 'niter': '--n_iter 50000'}),
    # ('r10_vgp', 'mignot,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 10', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r10_vgp', 'niter': '--n_iter 50000'}),
    # ('r15_vgp', 'mignot,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 15', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r15_vgp', 'niter': '--n_iter 50000'}),
    # ('r30_vgp', 'mignot,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 30', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r30_vgp', 'niter': '--n_iter 50000'}),
    # ('r60_vgp', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 60', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r60_vgp', 'niter': '--n_iter 50000'}),
    # ('r150_vgp', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 150', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r150_vgp', 'niter': '--n_iter 50000'}),
    # ('r300_vgp', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 300', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r300_vgp', 'niter': '--n_iter 50000'}),
    # ('r600_vgp', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 600', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r600_vgp', 'niter': '--n_iter 50000'}),
    # ('r900_vgp', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 900', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r900_vgp', 'niter': '--n_iter 50000'}),
    # ('r1800_vgp', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 1800', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r1800_vgp', 'niter': '--n_iter 50000'}),
    # ('r2700_vgp', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 2700', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r2700_vgp', 'niter': '--n_iter 50000'}),
    # ('r3600_vgp', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 3600', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r3600_vgp', 'niter': '--n_iter 50000'}),
    # ('r5400_vgp', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 5400', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r5400_vgp', 'niter': '--n_iter 50000'}),
    # ('r7200_vgp', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 7200', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r7200_vgp', 'niter': '--n_iter 50000'}),
    # ('r01_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f all', 'inducing': '--inducing kmeans', 'resolution': '-r 01', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r01_ahc', 'niter': '--n_iter 50000'}),
    # ('r03_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f all', 'inducing': '--inducing kmeans', 'resolution': '-r 03', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r03_ahc', 'niter': '--n_iter 50000'}),
    # ('r05_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f all', 'inducing': '--inducing kmeans', 'resolution': '-r 05', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r05_ahc', 'niter': '--n_iter 50000'}),
    # ('r10_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f all', 'inducing': '--inducing kmeans', 'resolution': '-r 10', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r10_ahc', 'niter': '--n_iter 50000'}),
    # ('r15_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f all', 'inducing': '--inducing kmeans', 'resolution': '-r 15', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r15_ahc', 'niter': '--n_iter 50000'}),
    # ('r30_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f all', 'inducing': '--inducing kmeans', 'resolution': '-r 30', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r30_ahc', 'niter': '--n_iter 50000'}),
    # ('r60_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f all', 'inducing': '--inducing kmeans', 'resolution': '-r 60', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r60_ahc', 'niter': '--n_iter 50000'}),
    # ('r150_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f all', 'inducing': '--inducing kmeans', 'resolution': '-r 150', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r150_ahc', 'niter': '--n_iter 50000'}),
    # ('r300_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f all', 'inducing': '--inducing kmeans', 'resolution': '-r 300', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r300_ahc', 'niter': '--n_iter 50000'}),
    # ('r600_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f all', 'inducing': '--inducing kmeans', 'resolution': '-r 600', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r600_ahc', 'niter': '--n_iter 50000'}),
    # ('r900_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f all', 'inducing': '--inducing kmeans', 'resolution': '-r 900', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r900_ahc', 'niter': '--n_iter 50000'}),
    # ('r1800_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f all', 'inducing': '--inducing kmeans', 'resolution': '-r 1800', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r1800_ahc', 'niter': '--n_iter 50000'}),
    # ('r2700_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f all', 'inducing': '--inducing kmeans', 'resolution': '-r 2700', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r2700_ahc', 'niter': '--n_iter 50000'}),
    # ('r3600_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f all', 'inducing': '--inducing kmeans', 'resolution': '-r 3600', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r3600_ahc', 'niter': '--n_iter 50000'}),
    # ('r5400_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f all', 'inducing': '--inducing kmeans', 'resolution': '-r 5400', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r5400_ahc', 'niter': '--n_iter 50000'}),
    # ('r7200_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f all', 'inducing': '--inducing kmeans', 'resolution': '-r 7200', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r7200_ahc', 'niter': '--n_iter 50000'}),
    # ('r01_vgp_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 01', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r01_vgp_ahc', 'niter': '--n_iter 50000'}),
    # ('r03_vgp_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 03', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r03_vgp_ahc', 'niter': '--n_iter 50000'}),
    # ('r05_vgp_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 05', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r05_vgp_ahc', 'niter': '--n_iter 50000'}),
    # ('r10_vgp_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 10', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r10_vgp_ahc', 'niter': '--n_iter 50000'}),
    # ('r15_vgp_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 15', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r15_vgp_ahc', 'niter': '--n_iter 50000'}),
    # ('r30_vgp_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 30', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r30_vgp_ahc', 'niter': '--n_iter 50000'}),
    # ('r60_vgp_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 60', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r60_vgp_ahc', 'niter': '--n_iter 50000'}),
    # ('r150_vgp_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 150', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r150_vgp_ahc', 'niter': '--n_iter 50000'}),
    # ('r300_vgp_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 300', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r300_vgp_ahc', 'niter': '--n_iter 50000'}),
    # ('r600_vgp_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 600', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r600_vgp_ahc', 'niter': '--n_iter 50000'}),
    # ('r900_vgp_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 900', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r900_vgp_ahc', 'niter': '--n_iter 50000'}),
    # ('r1800_vgp_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 1800', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r1800_vgp_ahc', 'niter': '--n_iter 50000'}),
    # ('r2700_vgp_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 2700', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r2700_vgp_ahc', 'niter': '--n_iter 50000'}),
    # ('r3600_vgp_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 3600', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r3600_vgp_ahc', 'niter': '--n_iter 50000'}),
    # ('r5400_vgp_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 5400', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r5400_vgp_ahc', 'niter': '--n_iter 50000'}),
    # ('r7200_vgp_ahc', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model vgp', 'feature_set': '-f all', 'resolution': '-r 7200', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r7200_vgp_ahc', 'niter': '--n_iter 50000'}),
    # ('r01_ahc_selected', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f selected', 'inducing': '--inducing kmeans', 'resolution': '-r 01', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r01_ahc_selected', 'niter': '--n_iter 50000'}),
    # ('r03_ahc_selected', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f selected', 'inducing': '--inducing kmeans', 'resolution': '-r 03', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r03_ahc_selected', 'niter': '--n_iter 50000'}),
    # ('r05_ahc_selected', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f selected', 'inducing': '--inducing kmeans', 'resolution': '-r 05', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r05_ahc_selected', 'niter': '--n_iter 50000'}),
    # ('r10_ahc_selected', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f selected', 'inducing': '--inducing kmeans', 'resolution': '-r 10', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r10_ahc_selected', 'niter': '--n_iter 50000'}),
    # ('r15_ahc_selected', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f selected', 'inducing': '--inducing kmeans', 'resolution': '-r 15', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r15_ahc_selected', 'niter': '--n_iter 50000'}),
    # ('r30_ahc_selected', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f selected', 'inducing': '--inducing kmeans', 'resolution': '-r 30', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r30_ahc_selected', 'niter': '--n_iter 50000'}),
    # ('r60_ahc_selected', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f selected', 'inducing': '--inducing kmeans', 'resolution': '-r 60', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r60_ahc_selected', 'niter': '--n_iter 50000'}),
    # ('r150_ahc_selected', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f selected', 'inducing': '--inducing kmeans', 'resolution': '-r 150', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r150_ahc_selected', 'niter': '--n_iter 50000'}),
    # ('r300_ahc_selected', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f selected', 'inducing': '--inducing kmeans', 'resolution': '-r 300', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r300_ahc_selected', 'niter': '--n_iter 50000'}),
    # ('r600_ahc_selected', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f selected', 'inducing': '--inducing kmeans', 'resolution': '-r 600', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r600_ahc_selected', 'niter': '--n_iter 50000'}),
    # ('r900_ahc_selected', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f selected', 'inducing': '--inducing kmeans', 'resolution': '-r 900', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r900_ahc_selected', 'niter': '--n_iter 50000'}),
    # ('r1800_ahc_selected', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f selected', 'inducing': '--inducing kmeans', 'resolution': '-r 1800', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r1800_ahc_selected', 'niter': '--n_iter 50000'}),
    # ('r2700_ahc_selected', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f selected', 'inducing': '--inducing kmeans', 'resolution': '-r 2700', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r2700_ahc_selected', 'niter': '--n_iter 50000'}),
    # ('r3600_ahc_selected', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f selected', 'inducing': '--inducing kmeans', 'resolution': '-r 3600', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r3600_ahc_selected', 'niter': '--n_iter 50000'}),
    # ('r5400_ahc_selected', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f selected', 'inducing': '--inducing kmeans', 'resolution': '-r 5400', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r5400_ahc_selected', 'niter': '--n_iter 50000'}),
    ('r7200_ahc_selected', 'mignot,owners,gpu', '1-00:00', '5', '1', {'model': '-m avg_kw21', 'data_dir': '-d data/narco_features/avg_kw21_long_ahc', 'gp_model': '--gp_model svgp', 'feature_set': '-f selected', 'inducing': '--inducing kmeans', 'resolution': '-r 7200', 'folds': '-k 05', 'repeats': '-n 5', 'kernel': '-c rq', 'likelihood': '-l bernoulli', 'savedir': '-s experiments/r7200_ahc_selected', 'niter': '--n_iter 50000'}),
]
# fmt: on


def submit_job(jobname, partition, time, ncpus, gpus, command, *args):

    content = f"""#!/bin/bash
#
#SBATCH --job-name={jobname}
#SBATCH -p {partition}
#SBATCH --time={time}
#SBATCH --cpus-per-task={ncpus}
#SBATCH --gpus={gpus}
#SBATCH --output=/home/users/alexno/narcolepsy-detector/logs/{jobname}.out
#SBATCH --error=/home/users/alexno/narcolepsy-detector/logs/{jobname}.err
##################################################

# source $PI_HOME/miniconda3/bin/activate
# conda activate nml
# ml load cudnn/7.0.4
cd $HOME/narcolepsy-detector
. activate_env.sh

python train_gp_model.py {' '.join([v for v in command.values()])}
python evaluate_gp_model.py {command['data_dir']}/avg_kw21_long_r{command['resolution'][3:]}_unscaled.csv -e {command['savedir'][3:]}
"""

    #     print('')
    #     print('#######################################################################################')
    #     print(content)
    #     print('#######################################################################################')
    #     print('')
    with tempfile.NamedTemporaryFile(delete=False) as j:
        j.write(content.encode())
    os.system(f"sbatch {j.name}")


if __name__ == "__main__":

    print(f"Submitting {len(JOBS)} job(s) ...")
    for jobinfo in JOBS:
        submit_job(*jobinfo)

    print("All jobs have been submitted!")

# python train_gp_model.py {' '.join([v for v in command.values()])}
# python train_gp_model.py {' '.join([v for v in command.values()])}
# python evaluate_gp_model.py -d data/narco_features/avg_kw21_long_test_unscaled.csv -e {command['savedir'][3:]}
# python evaluate_gp_model.py -d data/narco_features/avg_kw21_long_r{command['resolution'][3:]}_test_unscaled.csv -e {command['savedir'][3:]}
# python evaluate_gp_model.py -d data/narco_features/avg_kw21_long_r{command['resolution'][3:]}_test_unscaled.csv -e {command['savedir'][3:]}
